### ISSUE TITLE
Delete scrobbles pop ups

### ISSUE THREAD

**Issue by Nowena** [gomgon/UserCSS#17]
They're not dark anymore, all look like this

https://imgur.com/fpR88HV

**Comment by Chafouinerie** [comment]
Same for "Add new video"

**Comment by Nowena** [comment]
Deleting shouts is also affected

**Comment by Kurogal** [comment]
Same for deleting Albums as well. 
I imagine that most pop ups like that are just broken.

**Comment by gomgon** [comment]
Hey, sorry for the delay.
This should be fixed now.
Thanks for the report.
