### ISSUE TITLE
Cannot install/update discogs stylesheet

### ISSUE THREAD

**Issue by Nowena** [gomgon/UserCSS#22]
I get the message 'Stylus failed to parse usercss: Invalid @var color: #f2b90d7d; is not a color'

**Comment by gomgon** [comment]
Sorry, I used the wrong color format for a couple var.
Fixed :)

**Comment by Nowena** [comment]
Now I get this similar message: 'Stylus failed to parse usercss:Invalid @var color: #916f08; is not a color'
