### ISSUE TITLE
Some white spaces and loading gif for shoutbox button

### ISSUE THREAD

**Issue by Nowena** [gomgon/UserCSS#5]
Hi, I love your last.fm dark theme. been using it since you were on userstyles.org

I wanted to report these white spaces

![Opera Snapshot_2019-07-14_193710_www last fm](https://user-images.githubusercontent.com/52898460/61191616-23494e00-a672-11e9-9646-e75bd1fae7cf.png)
![Opera Snapshot_2019-07-14_193757_www last fm](https://user-images.githubusercontent.com/52898460/61191618-2c3a1f80-a672-11e9-8ebc-b5a128b9f272.png)
![Opera Snapshot_2019-07-14_194324_www last fm](https://user-images.githubusercontent.com/52898460/61191622-33612d80-a672-11e9-9d19-13bc89783faf.png)

And this loading gif that doesn't appear when posting a shout

![Opera Snapshot_2019-07-14_194219_www last fm](https://user-images.githubusercontent.com/52898460/61191641-5c81be00-a672-11e9-8033-ab285396305b.png)
![Opera Snapshot_2019-07-14_194150_www last fm](https://user-images.githubusercontent.com/52898460/61191646-62779f00-a672-11e9-9b8b-6c299f06ae0d.png)

Thanks for keeping your theme alive and hope you can fix these soon!

**Comment by gomgon** [comment]
Hey, glad you like it!
Thanks for bringing those up, fixed.

**Comment by Nowena** [comment]
I found more white spaces and there are some buttons that are white

![Opera Snapshot_2019-07-15_121110_www last fm](https://user-images.githubusercontent.com/52898460/61235874-2db02a00-a6fc-11e9-9538-c94bc9bab43b.png)
![Opera Snapshot_2019-07-15_121208_www last fm](https://user-images.githubusercontent.com/52898460/61235875-2e48c080-a6fc-11e9-99aa-c78ea2af3cb6.png)
![Opera Snapshot_2019-07-15_121445_www last fm](https://user-images.githubusercontent.com/52898460/61235876-2e48c080-a6fc-11e9-8ef8-9aac9f1cc5cc.png)
![Opera Snapshot_2019-07-15_121545_www last fm](https://user-images.githubusercontent.com/52898460/61235877-2e48c080-a6fc-11e9-93a2-2a6126db1fd5.png)
![Opera Snapshot_2019-07-15_121744_www last fm](https://user-images.githubusercontent.com/52898460/61235878-2e48c080-a6fc-11e9-9d2b-bbf9b34cf371.png)
![Opera Snapshot_2019-07-15_122039_www last fm](https://user-images.githubusercontent.com/52898460/61235879-2e48c080-a6fc-11e9-91fe-54cc0e960cc2.png)
![Opera Snapshot_2019-07-15_122148_www last fm](https://user-images.githubusercontent.com/52898460/61235881-2ee15700-a6fc-11e9-984e-d37f49f6b2e2.png)
![Opera Snapshot_2019-07-15_122225_www last fm](https://user-images.githubusercontent.com/52898460/61235882-2ee15700-a6fc-11e9-9aee-9cd725fe86bc.png)
